#!/usr/bin/env python3
"""Generate 03-questions.json for chapter 079 — neuter lo."""
import json
from pathlib import Path

questions = [
    # b1: core nominalization (q1–q11)
    {
        "id": "q1",
        "type": "mcq_single",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "Что выражает конструкция lo bueno в фразе Lo bueno es que tenemos tiempo?",
        "choices": [
            {"id": "a", "text": "Конкретный предмет на столе", "feedback": "Нет: lo + прилагательное обобщает качество, а не называет вещь."},
            {"id": "b", "text": "Абстрактный аспект или оценку ситуации", "feedback": "Да: «хорошее / то, что хорошо» в общем смысле."},
            {"id": "c", "text": "Местоимение «его» перед прилагательным", "feedback": "Нет: здесь lo — нейтральный определитель, не «его»."},
            {"id": "d", "text": "Указание «это» как esto", "feedback": "Нет: esto указывает на предмет или ситуацию, lo + adj — на качество."},
        ],
        "correct_answer": "b",
        "explanation": "lo + прилагательное превращает качество в абстрактное «имя по смыслу»: хорошее, важное.",
        "tags": ["nominalization"],
    },
    {
        "id": "q2",
        "type": "fill_blank",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "Заполните пропуск: ___ importante es descansar. (нейтральный артикль для обобщения)",
        "correct_answer": "Lo",
        "explanation": "Для «важное / то, что важно» нужна модель lo + прилагательное.",
        "tags": ["lo_required"],
    },
    {
        "id": "q3",
        "type": "true_false",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "Конструкция lo + прилагательное называет абстрактный аспект, а не конкретный предмет.",
        "correct_answer": "true",
        "explanation": "lo нейтрализует прилагательное: рядом нет существительного для согласования.",
        "tags": ["abstract"],
    },
    {
        "id": "q4",
        "type": "error_spotting",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "Выберите предложение без ошибки в значении «главное — здоровье».",
        "choices": [
            {"id": "a", "text": "Importante es la salud."},
            {"id": "b", "text": "Lo importante es la salud."},
            {"id": "c", "text": "La importante es la salud."},
            {"id": "d", "text": "Esto importante es la salud."},
        ],
        "correct_answer": "b",
        "explanation": "Без lo фраза Importante es… не выражает обобщённое «важное».",
        "tags": ["error"],
    },
    {
        "id": "q5",
        "type": "matching",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "Соотнесите испанскую модель и смысл.",
        "pairs": [
            {"left": "lo bueno", "right": "хорошее, то что хорошо"},
            {"left": "lo importante", "right": "важное, то что важно"},
            {"left": "lo difícil de esta tarea", "right": "сложное в этой задаче"},
        ],
        "explanation": "Все три — нейтральная номинализация качества или аспекта.",
        "tags": ["matching"],
    },
    {
        "id": "q6",
        "type": "mcq_single",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "Почему нельзя сказать Importante es llegar a tiempo в смысле «важно прийти вовремя» как обобщение?",
        "choices": [
            {"id": "a", "text": "Потому что importante — только существительное", "feedback": "Нет: importante — прилагательное, но без lo модель неполная."},
            {"id": "b", "text": "Без lo не выражается нейтральная номинализация «важное»", "feedback": "Да: нужно lo importante es…"},
            {"id": "c", "text": "Потому что после es всегда нужен артикль el", "feedback": "Нет: дело не в el, а в отсутствии lo."},
            {"id": "d", "text": "Потому что llegar требует subjuntivo", "feedback": "Нет: проблема в конструкции с lo, не в наклонении."},
        ],
        "correct_answer": "b",
        "explanation": "Для обобщённого «важное / то, что важно» обязательна модель lo + прилагательное.",
        "tags": ["why_lo"],
    },
    {
        "id": "q7",
        "type": "fill_blank",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "Заполните: Hablemos de ___ importante. (нейтральный артикль перед прилагательным)",
        "correct_answer": "lo",
        "explanation": "«О главном» — hablar de lo importante, без существительного после lo.",
        "tags": ["de_lo"],
    },
    {
        "id": "q8",
        "type": "true_false",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "В lo bueno lo всегда переводится отдельным словом «это» в каждой фразе.",
        "correct_answer": "false",
        "explanation": "lo здесь не «это», а нейтральный определитель; смысл даёт вся конструкция.",
        "tags": ["translation"],
    },
    {
        "id": "q9",
        "type": "mcq_single",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 3,
        "prompt": "Чем lo + прилагательное отличается от la cosa importante?",
        "choices": [
            {"id": "a", "text": "Ничем, это синонимы", "feedback": "Нет: в la cosa importante есть конкретное существительное cosa."},
            {"id": "b", "text": "В lo + adj нет существительного — только абстрактное качество", "feedback": "Да: lo «оформляет» прилагательное без cosa."},
            {"id": "c", "text": "lo + adj всегда множественное число", "feedback": "Нет: lo + adj — ед. число, мужская форма прилагательного."},
            {"id": "d", "text": "la cosa importante — только разговорная форма", "feedback": "Нет: это другая синтаксическая модель с явным существительным."},
        ],
        "correct_answer": "b",
        "explanation": "lo + adj не согласуется с существительным, потому что его в модели нет.",
        "tags": ["contrast_cosa"],
    },
    {
        "id": "q10",
        "type": "mcq_single",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "Какой перевод ближе к No entiendo lo difícil de esta tarea?",
        "choices": [
            {"id": "a", "text": "Я не понимаю эту сложную задачу", "feedback": "Нет: речь об аспекте «сложное в задаче», не о всей задаче."},
            {"id": "b", "text": "Я не понимаю, в чём тут сложность этой задачи", "feedback": "Да: lo difícil de… выделяет аспект."},
            {"id": "c", "text": "Я не понимаю, кто сложный", "feedback": "Нет: lo difícil — не про человека."},
            {"id": "d", "text": "Я не понимаю самое сложное из всех задач", "feedback": "Нет: для «самого» нужно lo más difícil."},
        ],
        "correct_answer": "b",
        "explanation": "lo + adj + de уточняет аспект внутри чего-то конкретного.",
        "tags": ["de_aspect"],
    },
    {
        "id": "q11",
        "type": "true_false",
        "theory_block_id": "b1_theory_neuter_lo_core_nominalization",
        "difficulty": 2,
        "prompt": "В модели lo + прилагательное lo не согласуется с существительным, потому что существительного в этой конструкции нет.",
        "correct_answer": "true",
        "explanation": "lo «оформляет» прилагательное без отдельного существительного рядом.",
        "tags": ["no_noun"],
    },
    # b2: form (q12–q22)
    {
        "id": "q12",
        "type": "mcq_single",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Какая форма прилагательного нужна после lo в lo importante?",
        "choices": [
            {"id": "a", "text": "importante (муж. ед.)", "feedback": "Да: после lo — мужская форма ед. числа."},
            {"id": "b", "text": "importanta", "feedback": "Нет: женская форма после нейтрального lo не ставится."},
            {"id": "c", "text": "importantes", "feedback": "Нет: множественное число здесь не используется."},
            {"id": "d", "text": "la importante", "feedback": "Нет: артикль la не сочетается с lo в этой модели."},
        ],
        "correct_answer": "a",
        "explanation": "После lo прилагательное — в мужском роде ед. числа: lo importante, lo difícil.",
        "tags": ["form"],
    },
    {
        "id": "q13",
        "type": "fill_blank",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Заполните: Prefiero ___ sencillo. (нейтральный артикль + простой)",
        "correct_answer": "lo",
        "explanation": "«Предпочитаю простое» — lo sencillo; форма sencillo — муж. ед.",
        "tags": ["form"],
    },
    {
        "id": "q14",
        "type": "true_false",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Род соседнего существительного влияет на форму прилагательного после lo.",
        "correct_answer": "false",
        "explanation": "Модель нейтральная: lo importante не меняется из‑за tarea или situación.",
        "tags": ["agreement"],
    },
    {
        "id": "q15",
        "type": "error_spotting",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Найдите предложение без ошибки: «важное в проекте — срок».",
        "choices": [
            {"id": "a", "text": "Lo importanta del proyecto es el plazo."},
            {"id": "b", "text": "Lo importante del proyecto es el plazo."},
            {"id": "c", "text": "Los importantes del proyecto es el plazo."},
            {"id": "d", "text": "La importante del proyecto es el plazo."},
        ],
        "correct_answer": "b",
        "explanation": "После lo — importante, не importanta; не los/la.",
        "tags": ["error"],
    },
    {
        "id": "q16",
        "type": "matching",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Соотнесите шаблон и пример.",
        "pairs": [
            {"left": "lo + adj", "right": "lo bueno, lo malo"},
            {"left": "lo + adj + de", "right": "lo difícil del examen"},
            {"left": "en lo + adj", "right": "en lo posible"},
        ],
        "explanation": "Три частые формы: простая номинализация, уточнение через de, устойчивое en lo posible.",
        "tags": ["matching"],
    },
    {
        "id": "q17",
        "type": "mcq_single",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Как правильно: «хорошее в ситуации» как один абстрактный аспект?",
        "choices": [
            {"id": "a", "text": "los buenos de la situación", "feedback": "Нет: для абстрактного качества — lo + adj в ед. числе."},
            {"id": "b", "text": "lo bueno de la situación", "feedback": "Да: lo bueno de la situación."},
            {"id": "c", "text": "la buena de la situación", "feedback": "Нет: la buena — про конкретную «хорошую», не аспект."},
            {"id": "d", "text": "lo buena de la situación", "feedback": "Нет: нужны lo и форма bueno вместе правильно."},
        ],
        "correct_answer": "b",
        "explanation": "Абстрактное «хорошее в…» — lo bueno de…, не los buenos.",
        "tags": ["de"],
    },
    {
        "id": "q18",
        "type": "fill_blank",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Заполните: Lo raro ___ caso es el silencio. (предлог «в/из» для уточнения)",
        "correct_answer": "del",
        "explanation": "lo + adj + de + уточнение: lo raro del caso.",
        "tags": ["de"],
    },
    {
        "id": "q19",
        "type": "true_false",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Прилагательные на -e (importante, interesante) после lo имеют отдельную женскую форму.",
        "correct_answer": "false",
        "explanation": "После lo отдельного женского рода нет: lo importante, lo interesante.",
        "tags": ["e_ending"],
    },
    {
        "id": "q20",
        "type": "mcq_single",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 3,
        "prompt": "Выберите корректную фразу «я не понимаю, в чём сложность этой задачи».",
        "choices": [
            {"id": "a", "text": "No entiendo lo difícil de esta tarea.", "feedback": "Да: lo difícil de esta tarea — аспект задачи."},
            {"id": "b", "text": "No entiendo la difícil de esta tarea.", "feedback": "Нет: la difícil — не та модель для абстрактного аспекта."},
            {"id": "c", "text": "No entiendo los difícil de esta tarea.", "feedback": "Нет: неверное число и артикль."},
            {"id": "d", "text": "No entiendo lo difíciles de esta tarea.", "feedback": "Нет: после lo — difícil, не difíciles."},
        ],
        "correct_answer": "a",
        "explanation": "lo difícil de esta tarea — стандартная модель «сложное в этой задаче».",
        "tags": ["example"],
    },
    {
        "id": "q21",
        "type": "fill_blank",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Заполните: Lo ___ es la salud. (важный, муж. ед. после lo)",
        "correct_answer": "importante",
        "explanation": "Lo importante es la salud — форма importante не меняется на женский род.",
        "tags": ["importante"],
    },
    {
        "id": "q22",
        "type": "mcq_single",
        "theory_block_id": "b2_theory_lo_plus_adjective_form",
        "difficulty": 2,
        "prompt": "Почему после lo не ставят los buenos для «хорошего в ситуации»?",
        "choices": [
            {"id": "a", "text": "Потому что bueno не склоняется", "feedback": "Нет: bueno склоняется, но модель требует lo + ед. число."},
            {"id": "b", "text": "Абстрактный аспект — lo + adj в ед. числе, не множественное los/las", "feedback": "Да: lo bueno de la situación."},
            {"id": "c", "text": "Потому что situación женского рода", "feedback": "Нет: род существительного на lo + adj не влияет."},
            {"id": "d", "text": "Потому что bueno — только существительное", "feedback": "Нет: bueno здесь прилагательное."},
        ],
        "correct_answer": "b",
        "explanation": "Для одного абстрактного качества — lo bueno, не los buenos.",
        "tags": ["singular"],
    },
    # b3: discourse patterns (q23–q33)
    {
        "id": "q23",
        "type": "mcq_single",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Что означает каркас Lo bueno es que…?",
        "choices": [
            {"id": "a", "text": "«Хороший человек есть, что…»", "feedback": "Нет: lo bueno — не «хороший (человек)»."},
            {"id": "b", "text": "«Хорошо то, что…» / оценка стороны ситуации", "feedback": "Да: типичный дискурсивный каркас."},
            {"id": "c", "text": "«Самое лучшее, что…»", "feedback": "Нет: для «самого» нужно lo mejor / lo más."},
            {"id": "d", "text": "«Это хорошее, что…» с esto", "feedback": "Нет: для качества — lo, не esto bueno."},
        ],
        "correct_answer": "b",
        "explanation": "Lo bueno es que… — оценка ситуации: «хорошо то, что…».",
        "tags": ["discourse"],
    },
    {
        "id": "q24",
        "type": "fill_blank",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Заполните: Lo malo es ___ no hay entradas. (союз для придаточного)",
        "correct_answer": "que",
        "explanation": "Каркас Lo + adj + es que + …: Lo malo es que no hay entradas.",
        "tags": ["es_que"],
    },
    {
        "id": "q25",
        "type": "true_false",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Фраза Bueno es que tenemos tiempo — полный аналог Lo bueno es que tenemos tiempo.",
        "correct_answer": "false",
        "explanation": "Без lo нет нейтральной номинализации «хорошее (в том, что…)».",
        "tags": ["discourse"],
    },
    {
        "id": "q26",
        "type": "error_spotting",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Выберите естественный каркас оценки: «важно, чтобы ты пришёл рано».",
        "choices": [
            {"id": "a", "text": "Lo importante es que llegues pronto."},
            {"id": "b", "text": "Importante es que llegues pronto."},
            {"id": "c", "text": "Esto importante es que llegues pronto."},
            {"id": "d", "text": "El importante es que llegues pronto."},
        ],
        "correct_answer": "a",
        "explanation": "Lo importante es que… — частый каркас «важно, чтобы / главное — чтобы».",
        "tags": ["error"],
    },
    {
        "id": "q27",
        "type": "matching",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Соотнесите русскую часть и испанский каркас.",
        "pairs": [
            {"left": "хорошо то, что", "right": "Lo bueno es que"},
            {"left": "плохо то, что", "right": "Lo malo es que"},
            {"left": "сосредоточимся на главном", "right": "Centrémonos en lo esencial"},
        ],
        "explanation": "Три типичные речевые модели с lo + прилагательное.",
        "tags": ["matching"],
    },
    {
        "id": "q28",
        "type": "mcq_single",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Как сказать «поговорим о главном»?",
        "choices": [
            {"id": "a", "text": "Hablemos de lo importante.", "feedback": "Да: глагол + de + lo + adj."},
            {"id": "b", "text": "Hablemos de el importante.", "feedback": "Нет: el importante — про конкретного «важного»."},
            {"id": "c", "text": "Hablemos de la importante.", "feedback": "Нет: не та модель для абстрактного «главного»."},
            {"id": "d", "text": "Hablemos importante.", "feedback": "Нет: без lo и предлога de конструкция неполная."},
        ],
        "correct_answer": "a",
        "explanation": "После hablar de часто идёт lo + прилагательное без существительного.",
        "tags": ["hablar_de"],
    },
    {
        "id": "q29",
        "type": "fill_blank",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Заполните: Lo bueno es ___ podemos empezar de nuevo. (союз после es)",
        "correct_answer": "que",
        "explanation": "Lo bueno es que… — устойчивый каркас с que.",
        "tags": ["es_que"],
    },
    {
        "id": "q30",
        "type": "true_false",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Lo mejor de la película и lo bueno de la película выражают один и тот же смысл «хорошая сторона без сравнения».",
        "correct_answer": "false",
        "explanation": "mejor — суперлатив («лучшее»); lo bueno — просто «хорошее / хорошая сторона».",
        "tags": ["mejor_vs_bueno"],
    },
    {
        "id": "q31",
        "type": "mcq_single",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 3,
        "prompt": "Чем lo + прилагательное отличается от lo que + глагол?",
        "choices": [
            {"id": "a", "text": "lo que требует придаточное с глаголом; lo + adj — одно прилагательное", "feedback": "Да: lo que quiero es… vs lo importante es…"},
            {"id": "b", "text": "Это одна и та же конструкция", "feedback": "Нет: lo que + глагол — развёрнутое придаточное."},
            {"id": "c", "text": "lo + adj всегда с subjuntivo", "feedback": "Нет: наклонение зависит от контекста, не от lo vs lo que."},
            {"id": "d", "text": "lo que нельзя использовать с es", "feedback": "Нет: lo que quiero es paz — нормальная модель."},
        ],
        "correct_answer": "a",
        "explanation": "lo que + глагол — придаточное; в этой главе фокус на lo + одно прилагательное.",
        "tags": ["lo_que"],
    },
    {
        "id": "q32",
        "type": "fill_blank",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Заполните: Centrémonos en ___ esencial. (нейтральный артикль + «существенное»)",
        "correct_answer": "lo",
        "explanation": "Centrémonos en lo esencial — «сосредоточимся на главном».",
        "tags": ["en_lo"],
    },
    {
        "id": "q33",
        "type": "true_false",
        "theory_block_id": "b3_theory_lo_adjective_discourse_patterns",
        "difficulty": 2,
        "prompt": "Каркасы Lo bueno es que… и Lo malo es que… звучат естественно в устной и письменной речи.",
        "correct_answer": "true",
        "explanation": "Эти модели — обычный нейтральный регистр, не архаизм.",
        "tags": ["register"],
    },
    # b4: participle (q34–q44)
    {
        "id": "q34",
        "type": "mcq_single",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "Что означает lo dicho?",
        "choices": [
            {"id": "a", "text": "«То, что я сказал» (полное придаточное)", "feedback": "Нет: это скорее lo que he dicho."},
            {"id": "b", "text": "«Сказанное», «то, что было сказано»", "feedback": "Да: lo + participio номинализирует действие или результат."},
            {"id": "c", "text": "«Он сказал»", "feedback": "Нет: lo dicho — не глагольная форма."},
            {"id": "d", "text": "«Сказанная (жен.) вещь»", "feedback": "Нет: после lo — dicho (муж. ед.), не la dicha."},
        ],
        "correct_answer": "b",
        "explanation": "lo + participio: lo dicho, lo hecho — обобщённое действие или результат.",
        "tags": ["participle"],
    },
    {
        "id": "q35",
        "type": "fill_blank",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "Заполните: Respecto a ___ dicho, no tengo más comentarios. (нейтральный артикль)",
        "correct_answer": "lo",
        "explanation": "Respecto a lo dicho — «что касается сказанного».",
        "tags": ["lo_dicho"],
    },
    {
        "id": "q36",
        "type": "true_false",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "После lo причастие обычно стоит в мужской форме единственного числа.",
        "correct_answer": "true",
        "explanation": "lo hecho, lo previsto, lo aprendido — муж. ед.",
        "tags": ["form"],
    },
    {
        "id": "q37",
        "type": "error_spotting",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "Выберите корректную фразу «что касается сказанного на встрече».",
        "choices": [
            {"id": "a", "text": "Respecto a la dicho en la reunión."},
            {"id": "b", "text": "Respecto a lo dicho en la reunión."},
            {"id": "c", "text": "Respecto a lo que dicho en la reunión."},
            {"id": "d", "text": "Respecto a las dicho en la reunión."},
        ],
        "correct_answer": "b",
        "explanation": "Для «сказанного» — lo dicho, не la dicho и не lo que dicho.",
        "tags": ["error"],
    },
    {
        "id": "q38",
        "type": "matching",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "Соотнесите конструкцию и смысл.",
        "pairs": [
            {"left": "lo dicho", "right": "сказанное"},
            {"left": "lo hecho", "right": "сделанное"},
            {"left": "lo aprendido", "right": "выученное, усвоенное"},
        ],
        "explanation": "lo + participio называет действие или результат в обобщённом виде.",
        "tags": ["matching"],
    },
    {
        "id": "q39",
        "type": "mcq_single",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "Чем lo dicho отличается от lo que he dicho?",
        "choices": [
            {"id": "a", "text": "lo dicho короче: вся нагрузка в одном причастии", "feedback": "Да: lo que he dicho — развёрнутое придаточное с глаголом."},
            {"id": "b", "text": "lo dicho всегда про будущее", "feedback": "Нет: dicho — прошедшее причастие."},
            {"id": "c", "text": "lo que he dicho нельзя использовать", "feedback": "Нет: обе модели существуют, но разные."},
            {"id": "d", "text": "lo dicho требует женский род", "feedback": "Нет: dicho — муж. ед. после lo."},
        ],
        "correct_answer": "a",
        "explanation": "lo dicho — компактная номинализация; lo que he dicho — придаточное с подлежащим и глаголом.",
        "tags": ["lo_que"],
    },
    {
        "id": "q40",
        "type": "fill_blank",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "Заполните: Me quedo con ___ aprendido. (нейтральный артикль перед причастием)",
        "correct_answer": "lo",
        "explanation": "Me quedo con lo aprendido — «оставляю себе выученное».",
        "tags": ["aprendido"],
    },
    {
        "id": "q41",
        "type": "true_false",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "Конструкция lo que dicho — нормативный вариант вместо lo dicho.",
        "correct_answer": "false",
        "explanation": "lo que требует развёрнутого придаточного; правильно lo dicho или lo que he dicho.",
        "tags": ["lo_que"],
    },
    {
        "id": "q42",
        "type": "mcq_single",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 3,
        "prompt": "Выберите верное утверждение про Lo hecho, hecho está.",
        "choices": [
            {"id": "a", "text": "Это ошибка: нужно lo que hecho está", "feedback": "Нет: устойчивая пословица с lo hecho."},
            {"id": "b", "text": "lo hecho номинализирует «сделанное»", "feedback": "Да: «что сделано, то сделано»."},
            {"id": "c", "text": "hecho здесь — прилагательное bueno/hecho", "feedback": "Нет: hecho — participio pasado."},
            {"id": "d", "text": "lo здесь местоимение «его» перед глаголом", "feedback": "Нет: lo hecho — нейтральная номинализация, не lo vi."},
        ],
        "correct_answer": "b",
        "explanation": "Lo hecho — «сделанное»; пословица фиксирует модель lo + participio.",
        "tags": ["proverb"],
    },
    {
        "id": "q43",
        "type": "fill_blank",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "Заполните: Guarda ___ previsto para mañana. (нейтральный артикль + «предусмотренное»)",
        "correct_answer": "lo",
        "explanation": "lo previsto — «то, что предусмотрено / запланировано».",
        "tags": ["previsto"],
    },
    {
        "id": "q44",
        "type": "mcq_single",
        "theory_block_id": "b4_theory_lo_plus_participle",
        "difficulty": 2,
        "prompt": "Какая форма причастия нужна в lo hecho?",
        "choices": [
            {"id": "a", "text": "hecho (муж. ед.)", "feedback": "Да: после lo — hecho, не hecha."},
            {"id": "b", "text": "hecha", "feedback": "Нет: после нейтрального lo — муж. ед."},
            {"id": "c", "text": "hechos", "feedback": "Нет: множественное число не используется в этой модели."},
            {"id": "d", "text": "haciendo", "feedback": "Нет: нужно participio pasado, не gerundio."},
        ],
        "correct_answer": "a",
        "explanation": "После lo причастие — в мужской форме ед. числа: lo hecho, lo dicho.",
        "tags": ["participle_form"],
    },
    # b5: contrasts (q45–q55)
    {
        "id": "q45",
        "type": "mcq_single",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 2,
        "prompt": "El bueno del grupo es Pablo vs Lo bueno del grupo es la cooperación — в чём разница?",
        "choices": [
            {"id": "a", "text": "Первая — конкретный человек; вторая — абстрактный аспект", "feedback": "Да: el bueno — «хороший (из них)»; lo bueno — «хорошее в группе»."},
            {"id": "b", "text": "Обе фразы синонимичны", "feedback": "Нет: el/la + adj vs lo + adj — разные модели."},
            {"id": "c", "text": "lo bueno всегда про человека", "feedback": "Нет: lo bueno — про качество или аспект."},
            {"id": "d", "text": "el bueno нельзя использовать с del grupo", "feedback": "Нет: el bueno del grupo — нормальная конструкция про человека."},
        ],
        "correct_answer": "a",
        "explanation": "el/la + adj — конкретный человек или вещь; lo + adj — абстрактный аспект.",
        "tags": ["el_vs_lo"],
    },
    {
        "id": "q46",
        "type": "fill_blank",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 2,
        "prompt": "Заполните: Lo importante no es ___ más caro. (нейтральный артикль перед más)",
        "correct_answer": "lo",
        "explanation": "Lo importante no es lo más caro — контраст обычного качества и суперлатива.",
        "tags": ["lo_mas"],
    },
    {
        "id": "q47",
        "type": "true_false",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 2,
        "prompt": "Lo importante и lo más importante выражают одинаковую степень «самое из всех».",
        "correct_answer": "false",
        "explanation": "lo más importante добавляет «самое»; lo importante — без сравнения «самое».",
        "tags": ["lo_mas"],
    },
    {
        "id": "q48",
        "type": "error_spotting",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 3,
        "prompt": "Выберите предложение в значении «главное — прийти вовремя» (абстрактное).",
        "choices": [
            {"id": "a", "text": "El importante es llegar a tiempo."},
            {"id": "b", "text": "Lo importante es llegar a tiempo."},
            {"id": "c", "text": "La importante es llegar a tiempo."},
            {"id": "d", "text": "Los importantes es llegar a tiempo."},
        ],
        "correct_answer": "b",
        "explanation": "El importante звучит как «важный (человек)»; для «важного» как аспекта — lo importante es llegar a tiempo.",
        "tags": ["error"],
    },
    {
        "id": "q49",
        "type": "matching",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 2,
        "prompt": "Соотнесите модель и смысл.",
        "pairs": [
            {"left": "lo importante", "right": "важное, без «самое»"},
            {"left": "lo más importante", "right": "самое важное"},
            {"left": "el bueno del grupo", "right": "конкретный «хороший» в группе"},
        ],
        "explanation": "lo + adj — качество; lo más + adj — пик; el/la + adj — конкретный referent.",
        "tags": ["matching"],
    },
    {
        "id": "q50",
        "type": "mcq_single",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 2,
        "prompt": "Как отличить нейтральное lo в lo importante от местоимения lo в lo vi?",
        "choices": [
            {"id": "a", "text": "После lo в lo importante сразу прилагательное или причастие, не личный глагол", "feedback": "Да: lo vi — местоимение + глагол; lo importante — lo + adj."},
            {"id": "b", "text": "lo vi всегда пишется с заглавной буквы", "feedback": "Нет: регистр не различает функции."},
            {"id": "c", "text": "lo importante — только множественное число", "feedback": "Нет: lo importante — ед. число."},
            {"id": "d", "text": "lo vi нельзя перевести", "feedback": "Нет: lo vi — «я его/это видел»; функция другая."},
        ],
        "correct_answer": "a",
        "explanation": "Ориентир: сразу после lo — adj/participle (нейтральное) или глагол (местоимение).",
        "tags": ["pronoun"],
    },
    {
        "id": "q51",
        "type": "fill_blank",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 2,
        "prompt": "Заполните: Ya dije ___ necesario. (нейтральный артикль + «необходимое»)",
        "correct_answer": "lo",
        "explanation": "Ya dije lo necesario — «сказал необходимое»; lo + adj, не местоимение перед глаголом.",
        "tags": ["lo_necesario"],
    },
    {
        "id": "q52",
        "type": "true_false",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 2,
        "prompt": "Lo bueno и lo mejor — полные синонимы.",
        "correct_answer": "false",
        "explanation": "mejor — суперлатив от bueno; lo bueno — «хорошая сторона» без «лучшее из всех».",
        "tags": ["mejor"],
    },
    {
        "id": "q53",
        "type": "mcq_single",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 3,
        "prompt": "Чем lo + adj отличается от esto/eso?",
        "choices": [
            {"id": "a", "text": "esto/eso указывают на не названный предмет; lo + adj называют качество", "feedback": "Да: esto — «это»; lo importante — «важное»."},
            {"id": "b", "text": "esto нельзя использовать в разговоре", "feedback": "Нет: esto/eso — обычные указательные."},
            {"id": "c", "text": "lo + adj всегда требует esto перед ним", "feedback": "Нет: lo и esto — разные модели, не сочетаются так."},
            {"id": "d", "text": "Различий нет", "feedback": "Нет: указание vs номинализация качества."},
        ],
        "correct_answer": "a",
        "explanation": "esto/eso — указание на предмет или ситуацию; lo + adj — аспект или качество.",
        "tags": ["esto"],
    },
    {
        "id": "q54",
        "type": "mcq_single",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 2,
        "prompt": "Какой вариант выражает «хорошая сторона плана — начать сразу», а не «хороший (человек) плана»?",
        "choices": [
            {"id": "a", "text": "El bueno del plan es empezar ya.", "feedback": "Нет: el bueno — про конкретного «хорошего»."},
            {"id": "b", "text": "Lo bueno del plan es empezar ya.", "feedback": "Да: lo bueno — аспект плана."},
            {"id": "c", "text": "La buena del plan es empezar ya.", "feedback": "Нет: la buena — про конкретную «хорошую»."},
            {"id": "d", "text": "Lo más bueno del plan es empezar ya.", "feedback": "Нет: lo más bueno — «самое хорошее», другой смысл."},
        ],
        "correct_answer": "b",
        "explanation": "Аспект плана — lo bueno del plan; el bueno — про человека.",
        "tags": ["el_vs_lo"],
    },
    {
        "id": "q55",
        "type": "true_false",
        "theory_block_id": "b5_theory_lo_contrasts_el_la_lo_mas_pronoun",
        "difficulty": 2,
        "prompt": "В Lo importante no es lo más caro контрастируются нейтральное качество и суперлатив.",
        "correct_answer": "true",
        "explanation": "lo importante — «важное»; lo más caro — «самое дорогое».",
        "tags": ["contrast"],
    },
    # b6: ru traps (q56–q66)
    {
        "id": "q56",
        "type": "mcq_single",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "Типичная ошибка русскоязычных: Importante es descansar. Как исправить?",
        "choices": [
            {"id": "a", "text": "Lo importante es descansar.", "feedback": "Да: не пропускайте lo в модели «главное / важное»."},
            {"id": "b", "text": "La importante es descansar.", "feedback": "Нет: la importante — не абстрактное «важное»."},
            {"id": "c", "text": "Esto importante es descansar.", "feedback": "Нет: esto + adj — калька, нужно lo."},
            {"id": "d", "text": "El importante es descansar.", "feedback": "Нет: el importante — «важный (человек)», не аспект."},
        ],
        "correct_answer": "a",
        "explanation": "По аналогии с русским «важно…» lo часто пропускают; в испанском нужно lo importante es….",
        "tags": ["trap"],
    },
    {
        "id": "q57",
        "type": "fill_blank",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "Заполните: Lo ___ de la idea es su claridad. (хороший, муж. ед.)",
        "correct_answer": "bueno",
        "explanation": "Lo bueno de la idea — не lo buena; после lo — bueno.",
        "tags": ["trap"],
    },
    {
        "id": "q58",
        "type": "true_false",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "После нейтрального lo можно согласовать прилагательное с родом русского слова в переводе (lo importanta).",
        "correct_answer": "false",
        "explanation": "Правило: мужская форма ед. числа — lo importante, lo bueno.",
        "tags": ["trap"],
    },
    {
        "id": "q59",
        "type": "error_spotting",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "Выберите фразу про «хорошую сторону фильма», не про «хорошего (человека)».",
        "choices": [
            {"id": "a", "text": "El bueno de la película es la música."},
            {"id": "b", "text": "Lo bueno de la película es la música."},
            {"id": "c", "text": "La buena de la película es la música."},
            {"id": "d", "text": "Los buenos de la película es la música."},
        ],
        "correct_answer": "b",
        "explanation": "Аспект фильма — lo bueno de la película; el bueno — про конкретного «хорошего».",
        "tags": ["trap"],
    },
    {
        "id": "q60",
        "type": "matching",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "Соотнесите типичную ошибку и исправление.",
        "pairs": [
            {"left": "пропуск lo (Importante es…)", "right": "Lo importante es…"},
            {"left": "lo buena de la idea", "right": "Lo bueno de la idea"},
            {"left": "esto importante es…", "right": "Lo importante es…"},
        ],
        "explanation": "Три частые ловушки: пропуск lo, согласование по роду, калька с esto.",
        "tags": ["matching"],
    },
    {
        "id": "q61",
        "type": "mcq_single",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "Когда вместо lo bueno es que… ошибочно ставят lo más bueno es que…?",
        "choices": [
            {"id": "a", "text": "Когда смешивают нейтральное качество и суперлатив «самое»", "feedback": "Да: lo bueno — «хорошая сторона»; lo más bueno — «самое хорошее»."},
            {"id": "b", "text": "Когда говорят о конкретном человеке", "feedback": "Нет: тогда el bueno, не lo más bueno."},
            {"id": "c", "text": "Когда используют participio", "feedback": "Нет: participio — другая модель (lo dicho)."},
            {"id": "d", "text": "Никогда, это всегда взаимозаменяемо", "feedback": "Нет: más меняет смысл на «самое»."},
        ],
        "correct_answer": "a",
        "explanation": "lo bueno и lo más bueno — разные модели; más добавляет смысл «самое».",
        "tags": ["trap_mas"],
    },
    {
        "id": "q62",
        "type": "fill_blank",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "Заполните: ___ importante es la puntualidad. (исправьте кальку esto importante)",
        "correct_answer": "Lo",
        "explanation": "Для абстрактного «важное» — lo, не указательное esto.",
        "tags": ["esto_trap"],
    },
    {
        "id": "q63",
        "type": "true_false",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "Перед выбором между el/la + adj и lo + adj полезно спросить: называю конкретного человека/вещь или абстрактный аспект?",
        "correct_answer": "true",
        "explanation": "Это алгоритм из теории: аспект — lo + adj; конкретный referent — el/la + adj.",
        "tags": ["algorithm"],
    },
    {
        "id": "q64",
        "type": "mcq_single",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "Как исправить Esto importante es la puntualidad?",
        "choices": [
            {"id": "a", "text": "Lo importante es la puntualidad.", "feedback": "Да: для «важного» — lo, не esto."},
            {"id": "b", "text": "El importante es la puntualidad.", "feedback": "Нет: el importante — про человека."},
            {"id": "c", "text": "La importante es la puntualidad.", "feedback": "Нет: la importante — не абстрактное «важное»."},
            {"id": "d", "text": "Importante es la puntualidad.", "feedback": "Нет: пропущено lo."},
        ],
        "correct_answer": "a",
        "explanation": "Калька с «это» — типичная ошибка; нужно lo importante es….",
        "tags": ["esto_trap"],
    },
    {
        "id": "q65",
        "type": "fill_blank",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 2,
        "prompt": "Заполните: Lo bueno del viaje ___ la gente. (глагол «быть» в прошедшем, 3 л. ед.)",
        "correct_answer": "fue",
        "explanation": "Lo bueno del viaje fue la gente — эталонная модель lo bueno de.",
        "tags": ["trap_de"],
    },
    {
        "id": "q66",
        "type": "mcq_single",
        "theory_block_id": "b6_theory_ru_speaker_traps_neuter_lo",
        "difficulty": 3,
        "prompt": "Как различить lo dicho и lo que quise decir?",
        "choices": [
            {"id": "a", "text": "lo dicho — компактная номинализация; lo que quise decir — придаточное с глаголом", "feedback": "Да: не путайте lo + participio и lo que + глагол."},
            {"id": "b", "text": "Это одна конструкция", "feedback": "Нет: lo dicho и lo que quise decir — разные модели."},
            {"id": "c", "text": "lo dicho требует esto перед ним", "feedback": "Нет: lo dicho самодостаточно."},
            {"id": "d", "text": "lo que quise decir — только письменная форма", "feedback": "Нет: обе формы устойчивы в речи."},
        ],
        "correct_answer": "a",
        "explanation": "lo dicho vs lo que + глагол — частая ловушка для русскоязычных.",
        "tags": ["lo_que_trap"],
    },
]

out = Path(__file__).parent / "03-questions.json"
with open(out, "w", encoding="utf-8") as f:
    json.dump({"questions": questions}, f, ensure_ascii=False, indent=2)
print(f"Wrote {len(questions)} questions to {out}")
